#!/bin/bash

# Apps
spotify &
obsidian &
# teams-for-linux &

# Terminal Apps
# kitty --class btop btop &
kitty --class nvtop nvtop &
# ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &
